import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

BRAND_BLUE = colors.HexColor('#2563eb')
SLATE = colors.HexColor('#334155')
MUTED = colors.HexColor('#64748b')


def _styles():
    base = getSampleStyleSheet()
    return {
        'title': ParagraphStyle('ReportTitle', parent=base['Title'], textColor=BRAND_BLUE, fontSize=22, spaceAfter=4),
        'meta': ParagraphStyle('Meta', parent=base['Normal'], textColor=MUTED, fontSize=9, spaceAfter=16),
        'h2': ParagraphStyle('H2', parent=base['Heading2'], textColor=SLATE, fontSize=13, spaceBefore=4, spaceAfter=6),
        'body': ParagraphStyle('Body', parent=base['BodyText'], textColor=SLATE, fontSize=10.5, leading=15, spaceAfter=10),
        'headline': ParagraphStyle('Headline', parent=base['Heading3'], textColor=BRAND_BLUE, fontSize=12, spaceBefore=14, spaceAfter=4),
        'explanation': ParagraphStyle('Explanation', parent=base['BodyText'], textColor=SLATE, fontSize=10.5, leading=15, leftIndent=10, spaceAfter=4),
    }


def build_insights_pdf(report_data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        topMargin=0.85 * inch, bottomMargin=0.85 * inch,
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
    )
    styles = _styles()
    story = []

    story.append(Paragraph(report_data.get('title') or 'Procurement Insights Report', styles['title']))
    generated_at = datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')
    story.append(Paragraph(f'Generated by Procure.ai &middot; {generated_at}', styles['meta']))
    story.append(HRFlowable(width='100%', thickness=0.75, color=colors.HexColor('#e2e8f0'), spaceAfter=14))

    documents = report_data.get('documents') or []
    if documents:
        story.append(Paragraph('Documents Covered', styles['h2']))
        rows = [['Document', 'Type']] + [[d.get('name', 'Unknown'), d.get('type', 'unknown')] for d in documents]
        table = Table(rows, colWidths=[3.8 * inch, 2.2 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#eff6ff')),
            ('TEXTCOLOR', (0, 0), (-1, 0), BRAND_BLUE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9.5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(table)
        story.append(Spacer(1, 16))

    overview = report_data.get('overview')
    if overview:
        story.append(Paragraph('Executive Overview', styles['h2']))
        story.append(Paragraph(overview, styles['body']))

    headlines = report_data.get('headlines') or []
    if headlines:
        story.append(Paragraph('Key Findings', styles['h2']))
        for idx, item in enumerate(headlines, start=1):
            headline_text = item.get('headline', f'Finding {idx}') if isinstance(item, dict) else str(item)
            story.append(Paragraph(f'{idx}. {headline_text}', styles['headline']))
            explanation = item.get('explanation', '') if isinstance(item, dict) else ''
            if explanation:
                story.append(Paragraph(explanation, styles['explanation']))
    else:
        story.append(Spacer(1, 8))
        story.append(Paragraph('No key findings available yet — upload a contract or spreadsheet to generate insights.', styles['body']))

    doc.build(story)
    return buffer.getvalue()
