import { useState } from 'react';
import { Sparkles, Loader2, AlertTriangle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { getSapInsight } from '../services/api';

/**
 * On-demand AI executive insight for a dashboard section. The narrative is
 * generated by the backend strictly over the section's already-computed
 * metrics, so it can never contradict the stat cards beside it.
 *
 * Kept on-demand (a button, not auto-run) so the deterministic cards render
 * instantly and the LLM call only happens when the user wants the narrative.
 */
const SapInsightPanel = ({ section }) => {
  const [state, setState] = useState({ status: 'idle', text: '' });

  const generate = async () => {
    setState({ status: 'loading', text: '' });
    try {
      const res = await getSapInsight({
        section,
        providerKey: localStorage.getItem('procure_ai_provider_key') || 'auto',
      });
      if (res.insight) setState({ status: 'done', text: res.insight });
      else setState({ status: 'error', text: res.error || 'Insight unavailable.' });
    } catch (err) {
      setState({ status: 'error', text: err.message || 'Insight request failed.' });
    }
  };

  return (
    <div className="mt-6 rounded-2xl border border-sky-100 bg-sky-50/50 p-5">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-sky-800">
          <Sparkles size={16} />
          <p className="text-sm font-semibold">AI Executive Insight</p>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={state.status === 'loading'}
          className="inline-flex items-center gap-1.5 rounded-full bg-sky-600 px-4 py-1.5 text-xs font-semibold text-white transition hover:bg-sky-700 disabled:opacity-50"
        >
          {state.status === 'loading' ? (
            <><Loader2 size={13} className="animate-spin" /> Analyzing…</>
          ) : (
            <><Sparkles size={13} /> {state.status === 'done' ? 'Regenerate' : 'Generate'}</>
          )}
        </button>
      </div>

      {state.status === 'done' && (
        <div className="prose prose-sm mt-3 max-w-none text-slate-700">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{state.text}</ReactMarkdown>
        </div>
      )}
      {state.status === 'error' && (
        <p className="mt-3 flex items-start gap-2 text-sm text-amber-700">
          <AlertTriangle size={15} className="mt-0.5 shrink-0" />
          {state.text}
        </p>
      )}
      {state.status === 'idle' && (
        <p className="mt-2 text-xs text-slate-500">
          Generate a grounded, plain-language summary of the metrics above.
        </p>
      )}
    </div>
  );
};

export default SapInsightPanel;
